"use server";
import { revalidatePath } from "next/cache"; import { redirect } from "next/navigation";
import { requireContentManager } from "@/features/auth/server"; import { createServerSupabaseClient } from "@/lib/supabase/server";
import { validateProfileFormData, type ProfileActionState, type ProfileFormValues } from "./validation";
const payload = (v: ProfileFormValues) => ({ slug: v.slug, name: v.name, position: v.position, summary: v.summary, details: v.details, skills: v.skills, image_url: v.imageUrl, github_url: v.githubUrl, website_url: v.websiteUrl, is_published: v.isPublished, sort_order: v.sortOrder });
const refresh = (slug?: string) => { revalidatePath("/profiles"); revalidatePath("/admin/profiles"); if (slug) revalidatePath(`/profiles/${slug}`); };
export async function createProfileAction(_: ProfileActionState, data: FormData): Promise<ProfileActionState> { await requireContentManager(); const checked = validateProfileFormData(data); if (!checked.ok) return checked.state; const db = await createServerSupabaseClient(); const result = await db.from("member_profiles").insert(payload(checked.values)).select("id,slug").single(); if (result.error) return { status: "error", message: result.error.code === "23505" ? "이미 사용 중인 slug입니다." : "프로필을 추가하지 못했습니다." }; refresh(result.data.slug); redirect(`/admin/profiles/${result.data.id}/edit?created=1`); }
export async function updateProfileAction(_: ProfileActionState, data: FormData): Promise<ProfileActionState> { await requireContentManager(); const checked = validateProfileFormData(data); if (!checked.ok) return checked.state; const db = await createServerSupabaseClient(); const result = await db.from("member_profiles").update(payload(checked.values)).eq("id", checked.values.id).eq("updated_at", checked.values.updatedAt ?? "").select("id,slug").maybeSingle(); if (result.error || !result.data) return { status: "error", message: "저장하지 못했습니다. 새로고침 후 다시 시도해 주세요." }; refresh(result.data.slug); redirect(`/admin/profiles/${result.data.id}/edit?saved=1`); }
export async function deleteProfileAction(data: FormData): Promise<never> { await requireContentManager(); const id = String(data.get("id") ?? ""); const slug = String(data.get("slug") ?? ""); const db = await createServerSupabaseClient(); const { error } = await db.from("member_profiles").delete().eq("id", id); if (error) redirect(`/admin/profiles/${id}/edit?error=delete`); refresh(slug); redirect("/admin/profiles?deleted=1"); }
